### ISSUE TITLE
Main nav

### ISSUE THREAD

**Issue by simonwinter** [dragonfly-science/dragonfly-website#152]
The main nav includes the following components:

+ Logo/Home
+ Navigation with 2 levels (including drop down)
+ Get in touch link to the right which takes user down to the footer.
+ Responsive version (hamburger to the right, opens full screen menu).

> There will need to be some restructuring of html & some more html5/semantic markup.

---

**Todo:** 

- [x] Set up flexbox based menu.
- [x] Set up responsive menu.
- [x] Test breakpoint - somewhere between `sm` and `md`
