### ISSUE TITLE
What we do section pages

### ISSUE THREAD

**Issue by simonwinter** [dragonfly-science/dragonfly-website#204]
**Description:**

The individual landing pages of this section need to have the body copy updated.

At some point last year we embarked on writing this section - I'm not sure where we got to @sarah-wilcox?

---

**Staging URLs:** 

- http://dragonfly-website-staging.dragonfly-science.reports.dragonfly.co.nz/what-we-do/statistical-analysis-and-machine-learning.html
- http://dragonfly-website-staging.dragonfly-science.reports.dragonfly.co.nz/what-we-do/systems-for-data.html
- http://dragonfly-website-staging.dragonfly-science.reports.dragonfly.co.nz/what-we-do/sound-decision-making.html
- http://dragonfly-website-staging.dragonfly-science.reports.dragonfly.co.nz/what-we-do/upskilling-your-team.html

---

**Tasks**

- [ ] @finlay to chat with @sarah-wilcox & re-brief if necessary
- [ ] Statistical analysis and machine learning copy updated
- [ ] Systems for data copy updated
- [ ] Evidence for sound decision-making copy updated
- [ ] Upskilling your team copy updated
