### ISSUE TITLE
Case Studies

### ISSUE THREAD

**Issue by simonwinter** [dragonfly-science/dragonfly-website#205]
**Description:**

The case studies are largely out of date & need to be reviewed/culled/added.

@finlay to brief @sarah-wilcox on a few (perhaps 6) projects which we'd like case studies written for.
The new case studies will require imagery & potential interviews with clients.

@simon to remove case studies filters.

---

**Tasks**

- [ ] @finlay to brief @sarah-wilcox 
- [ ] @sarah-wilcox to propose template/format of case studies 
- [ ] @sarah-wilcox to provide case study content & @finlay to approve
- [ ] @sarah-wilcox & @pepzuijderwijk to work on images
