### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by simonwinter** [dragonfly-science/dragonfly-website#207]
**Description:**

There are a few structural changes to the page:

- remove blue section
- add in the design as per Pep’s tiled layout (left/right panels linking to what we do, who we are & our work)
- restrict “news” section to max. 4 articles
- set up testimonials section

Each of the tiled panels on the page will require a thumbnail image & will display the title text as found in the header sections of each of these sections.

---

**Tasks**

- [ ] @simonwinter to implement design changes
- [ ] @pep to suggest thumbnail images for each of the new tiles
- [ ] @sarah-wilcox to collate existing testimonials we can use for the homepage testimonial carousel

---

**Related:**

- Home page video #210
