### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by simonwinter** [dragonfly-science/dragonfly-website#208]
**Description:**

We have a number of placeholder images in the site that need replacing; additionally there are low quality images that need to be replaced as well.

_**Note:**_ 
- Hero images are cropped to 1600 x 1000
- Thumbnails are cropped to 960 x 960 (we may add responsive images at 480 x 480 as well, if we have the original, then we can just resize this image on the server)

**What we do:**

http://dragonfly-website-staging.dragonfly-science.reports.dragonfly.co.nz/what-we-do/

- [ ] Main header (correct image?)
- [ ] Sub section teaser & header images

**Who we are:**

- [ ] Main header (correct image?)
- [ ] Thumbnails for each person
- [ ] Hero images for each person
- [ ] Update Finlay's images

The thumbnails & hero images for each person need to be more consistent (positioning & size of head within frame, colour grading etc.)

**Our work:**

Once the case studies have been finalised, we will need to review the images used for each. (see issue #205)

---

**Tasks**

- [ ] @pepzuijderwijk to correct all images
